# load configuration
# -----------------------------------------------------
configfile: "config/config.yml"


# load rules
# -----------------------------------------------------
include: "rules/common.smk"
include: "rules/process_reads.smk"
include: "rules/bowtie2.smk"
include: "rules/bwamem2.smk"
include: "rules/star.smk"
include: "rules/minimap2.smk"
include: "rules/process_alignment.smk"
include: "rules/mapping_stats.smk"
include: "rules/bcftools.smk"
include: "rules/freebayes.smk"
include: "rules/variant_annotation.smk"
include: "rules/qc.smk"
include: "rules/report.smk"


# container definition (optional)
# -----------------------------------------------------
containerized: "oras://ghcr.io/mpusp/snakemake-simple-mapping:latest"


# optional messages, log and error handling
# -----------------------------------------------------
onstart:
    print("\n--- Analysis started ---\n")


onsuccess:
    print("\n--- Workflow finished! ---\n")


onerror:
    print("\n--- An error occurred! ---\n")


# target rules
# -----------------------------------------------------
rule all:
    default_target: True
    input:
        "results/multiqc/multiqc_report.html",
        expand(
            "results/report/{caller}_report.pdf",
            caller=config["variant_calling"]["tool"],
        ),
        expand(
            "results/processed_alignment/cram/{sample}.cram.crai", sample=samples.index
        ),
