$schema: "https://json-schema.org/draft/2020-12/schema"
description: configuration file for the analysis pipeline
properties:
  samplesheet:
    type: string
    description: path to the sample sheet in tsv format
  get_genome:
    type: object
    properties:
      database:
        type: string
        description: database to use for genome retrieval, 'ncbi' or 'manual'
        default: ncbi
      assembly:
        type: string
        description: RefSeq assembly accession to use for genome retrieval
        default: GCF_000307535.1
      fasta:
        type: [string, "null"]
        description: path to a custom FASTA file (optional)
    required:
      - database
      - assembly
  mapping:
    type: object
    properties:
      tool:
        type: string
        description: mapping tool to use, one of 'bowtie2', 'bwa_mem2', 'star', or 'minimap2'
        default: bwa_mem2
      bowtie2:
        type: object
        properties:
          index:
            type: string
            description: additional arguments to bowtie build
          extra:
            type: string
            description: additional arguments to bowtie align
      bwa_mem2:
        type: object
        properties:
          extra:
            type: string
            description: additional arguments to bwa-mem2
          sort:
            type: string
            description: sorting tool to use, e.g. 'samtools'
            default: samtools
          sort_order:
            type: string
            description: sorting order to use
            default: coordinate
          sort_extra:
            type: string
            description: additional arguments to pass to the sorting tool
      star:
        type: object
        properties:
          index:
            type: string
            description: additional arguments to STAR index
          extra:
            type: array
            items:
              type: string
            description: additional arguments to STAR align
            default: ["--outFilterMultimapNmax 10", "--outSAMmultNmax 1", "--outMultimapperOrder Random", "--alignIntronMax 1"]
      minimap2:
        type: object
        properties:
          index:
            type: string
            description: additional arguments to minimap2 index
          extra:
            type: string
            description: additional arguments to minimap2 align
            default: -ax map-ont
          sorting:
            type: string
            description: sorting order to use
            default: coordinate
          sort_extra:
            type: string
            description: additional arguments to pass to the sorting tool
  mapping_postprocessing:
    type: object
    properties:
      samtools_sort:
        type: object
        properties:
          extra:
            type: string
            description: additional arguments to pass to Samtools sort
            default: -m 4G
      samtools_index:
        type: object
        properties:
          extra:
            type: string
            description: additional arguments to pass to Samtools index
      deduplication:
        type: object
        properties:
          enabled:
            type: boolean
            description: whether to enable deduplication
            default: false
          tool:
            type: string
            description: deduplication tool to use, one of 'umi_tools', "samtools_markdup", or "picard_markduplicates"
            default: umi_tools
          umi_tools:
            type: object
            properties:
              extra:
                type: string
                description: additional arguments to pass to umi_tools dedup
        required:
          - enabled
  mapping_stats:
    type: object
    properties:
      gffread:
        type: object
        properties:
          extra:
            type: string
            description: additional arguments to pass to GFFread
      rseqc_infer_experiment:
        type: object
        properties:
          extra:
            type: string
            description: additional arguments to pass to RSeQC infer_experiment.py
      rseqc_bam_stat:
        type: object
        properties:
          extra:
            type: string
            description: additional arguments to pass to RSeQC bam_stat.py
      deeptools_coverage:
        type: object
        properties:
          genome_size:
            type: integer
            description: genome size in base pairs
            default: 1000
          extra:
            type: string
            description: additional arguments to pass to DeepTools bamCoverage
    required:
      - gffread
      - rseqc_infer_experiment
      - rseqc_bam_stat
      - deeptools_coverage
required:
  - samplesheet
  - get_genome
  - mapping
  - mapping_stats
