samplesheet: "config/samples.tsv"

# Configs for obtaining genome sequence and annotation
genome:
  strep:
    source: "ncbi" # local vs ncbi database
    prefix: "strep"
    local:
      fasta: "data/strep.fasta"
      gff: "data/strep.gff3"
    datasets:
      genbank: "CP003901.1"
      assembly: ""
      extra: ""

# Configs for alignment tools
mapping:
  fastq_dir: "data"
  tool: "bwa_mem2"
  bowtie2:
    index: ""
    extra: ""
  bwa_mem2:
    extra: ""
    sort: "samtools"
    sort_order: "coordinate"
    sort_extra: ""
  star:
    index: ""
    extra: ["--outFilterMultimapNmax 10", "--outSAMmultNmax 1", "--outMultimapperOrder Random", "--alignIntronMax 1"]
  minimap2:
    index: ""
    extra: "-ax map-ont"
    sorting: "coordinate"
    sort_extra: ""

# Configs for processing post-alignment
mapping_postprocessing:
  samtools_sort:
    extra: "-m 4G"
  samtools_index:
    extra: ""
  deduplication:
    enabled: true
    tool: "picard"
    umi_tools:
      extra: "" # or directional, cluster, adjacency, etc.
    samtools:
      extra: "-c -r --no-PG"
    picard:
      extra: ""

# Configs for mapping statistics
mapping_stats:
  gffread:
    extra: ""
  rseqc_infer_experiment:
    extra: ""
  rseqc_bam_stat:
    extra: ""
  deeptools_coverage:
    genome_size: 1000
    extra: ""

# Configs for multiqc
qc:
  multiqc:
    extra: "--verbose --dirs"
