samplesheet: "config/samples.tsv"
get_genome:
  database: "ncbi"
  assembly: "GCF_000307535.1"
  fasta: Null
mapping:
  tool: "bwa_mem2"
  bowtie2:
    index: ""
    extra: ""
  bwa_mem2:
    extra: ""
    sort: "samtools"
    sort_order: "coordinate"
    sort_extra: ""
  star:
    index: ""
    extra: ["--outFilterMultimapNmax 10", "--outSAMmultNmax 1", "--outMultimapperOrder Random", "--alignIntronMax 1"]
  minimap2:
    index: ""
    extra: "-ax map-ont"
    sorting: "coordinate"
    sort_extra: ""
mapping_postprocessing:
  samtools_sort:
    extra: "-m 4G"
  samtools_index:
    extra: ""
  deduplication:
    enabled: false
    tool: "umi_tools"
    umi_tools:
      extra: "" # or directional, cluster, adjacency, etc.
    samtools:
      extra: "-c -r --no-PG"
    picard:
      extra: ""
mapping_stats:
  gffread:
    extra: ""
  rseqc_infer_experiment:
    extra: ""
  rseqc_bam_stat:
    extra: ""
  deeptools_coverage:
    genome_size: 1000
    extra: ""
qc:
  multiqc:
    extra: "--verbose --dirs"